---
# tasks file for ansible/roles/client-ci

- name: Build dev image
  docker_image:
    name: '{{ image_name }}'
    tag: dev
    build:
      path: '{{ client_dir }}'
      dockerfile: 'Dockerfile.dev'
      pull: no
      rm: yes
    source: build
    state: present

- name: Start the container
  docker_container:
    name: '{{ container_name }}'
    image: '{{ image_name }}:dev'
    interactive: yes
    state: started

- name: Lint
  docker_container:
    detach: false
    name: '{{ container_name }}'
    command: '{{ lint_cmd }}'
  register: lint_output

- name: Show test output
  debug:
    var: lint_output.ansible_facts.docker_container.Output

- name: UnitTests
  docker_container:
    detach: false
    name: '{{ container_name }}'
    command: '{{ test_cmd }}'
  register: test_output

- name: Show test output
  debug:
    var: test_output.ansible_facts.docker_container.Output

- name: Build
  docker_container:
    detach: false
    name: '{{ container_name }}'
    command: '{{ build_cmd }}'
  register: build_output

- name: Show test output
  debug:
    var: build_output.ansible_facts.docker_container.Output

- name: Stop the container
  docker_container:
    name: '{{ container_name }}'
    state: stopped

- name: Delete the container
  docker_container:
    name: '{{ container_name }}'
    state: absent
