version: '3.7'

services:

  client:
    image: $CLIENT_IMAGE_NAME
    container_name: $CLIENT_CONTAINER_NAME
    build: client/
    ports:
      - 3100:80

  docs:
    image: $DOCS_IMAGE_NAME
    container_name: $DOCS_CONTAINER_NAME
    build: docs/
    ports:
      - 3200:3200

  db:
    image: $POSTRGES_IMAGE_NAME
    container_name: $POSTRGES_CONTAINER_NAME
    build: db/
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
      - 5432:5432
    volumes:
      - ./:/var/lib/postgresql/data
    restart: always

  adminer:
    image: $ADMINER_IMAGE_NAME
    container_name: $ADMINER_CONTAINER_NAME
    ports:
      - 8080:8080
    restart: always
