version: '3.7'

services:
  client:
    image: $CLIENT_IMAGE_NAME
    container_name: $CLIENT_CONTAINER_NAME
    build: client/
    ports:
      - $CLIENT_LIVE_PORT:$NGINX_PORT

  docs:
    image: $DOCS_IMAGE_NAME
    container_name: $DOCS_CONTAINER_NAME
    build: docs/
    ports:
      - $DOCS_LIVE_PORT:$NGINX_PORT

  db:
    image: $POSTRGES_IMAGE_NAME
    container_name: $POSTRGES_CONTAINER_NAME
    build: db/
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: $ADMINER_IMAGE_NAME
    container_name: $ADMINER_CONTAINER_NAME
    ports:
      - $ADMINER_PORT:$ADMINER_PORT
    restart: always
