allow_k8s_contexts('docker-desktop')

docker_build('reading-todo/client', '../client')
docker_build('reading-todo/docs', '../docs')

k8s_resource('client', port_forwards=3300)
k8s_resource('docs', port_forwards=3100)

k8s_yaml(helm('.'))
watch_file('..')
