---
# vars file for ansible/roles/client-ci

client_dir: '../client/'
image_name: 'reading-todo/client'
container_name: 'reading_todo_client_dev'
lint_cmd: 'npm run lint'
test_cmd: 'npm run test:ci'
build_cmd: 'npm run build'
