memoryrequest: '200Mi'
cpurequest: '0.1'
memorylimit: '1Gi'
cpulimit: '1.5'

client:
  name: client
  image: reading-todo/client
  portType: NodePort

docs:
  name: docs
  image: reading-todo/docs
  portType: NodePort

postgres:
  name: postgres
  image: reading-todo/postgres
  subdomain: postgres
  svcname: postgres-svc
  portType: NodePort

adminer:
  name: adminer
  image: adminer
  subdomain: adminer
  svcname: adminer-svc
  portType: NodePort
