---
# tasks file for compose

- name: Tear down existing services
  docker_compose:
    project_src: '{{ project_src }}'
    state: absent

- name: Create and start services
  docker_compose:
    project_src: '{{ project_src }}'
    build: yes
  register: output

- debug:
    var: output

- name: Services containers are running
  assert:
    that:
      - 'client.{{ client_container_name }}.state.running'
      - 'docs.{{ docs_container_name }}.state.running'
      - 'db.{{ postgres_container_name }}.state.running'
      - 'adminer.{{ adminer_container_name }}.state.running'
