apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: '{{ .Values.client.name }}'
spec:
  replicas: 1
  template:
    metadata:
      name: '{{ .Values.client.name }}'
      labels:
        app: '{{ .Values.client.name }}'
    spec:
      containers:
        - name: '{{ .Values.client.name }}'
          image: '{{ .Values.client.image }}'
          imagePullPolicy: Always
          resources:
            requests:
              memory: '{{ .Values.memoryrequest }}'
              cpu: '{{ .Values.cpurequest }}'
            limits:
              memory: '{{ .Values.memorylimit }}'
              cpu: '{{ .Values.cpulimit }}'
          ports:
            - containerPort: 3300
              protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: docker-desktop
