apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      name: client
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: '{{ .Values.client }}'
          imagePullPolicy: Always
          resources:
            requests:
              memory: '{{ .Values.memoryrequest }}'
              cpu: '{{ .Values.cpurequest }}'
            limits:
              memory: '{{ .Values.memorylimit }}'
              cpu: '{{ .Values.cpulimit }}'
          env:
            - name: no_proxy
              value: 'localhost,127.0.0.1'
          ports:
            - containerPort: 80
              protocol: TCP
