apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: '{{ .Values.postgres.name }}'
spec:
  replicas: 1
  template:
    metadata:
      name: '{{ .Values.postgres.name }}'
      labels:
        name: '{{ .Values.postgres.name }}'
    spec:
      hostname: '{{ .Values.postgres.name }}'
      subdomain: '{{ .Values.postgres.subdomain }}'
      containers:
        - name: '{{ .Values.postgres.name }}'
          image: '{{ .Values.postgres.image }}'
          imagePullPolicy: Always
          resources:
            requests:
              memory: '{{ .Values.memoryrequest }}'
              cpu: '{{ .Values.cpurequest }}'
            limits:
              memory: '{{ .Values.memorylimit }}'
              cpu: '{{ .Values.cpulimit }}'
          ports:
            - containerPort: 5432
              protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: docker-desktop
