apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.postgres.subdomain }}'
spec:
  clusterIp: None
  selector:
    name: '{{ .Values.postgres.name }}'
  ports:
    - name: postgres-ports # Actually, no port is needed.
      port: 2345
      targetPort: 2345
      protocol: TCP
