---
- hosts: localhost
  connection: local

  roles:
    - { role: 'python-deps', tags: 'ansible' }
    - { role: 'client-ci', tags: 'ci' }
    - { role: 'client', tags: 'client' }
# ansible-playbook playbook.yml -i hosts.yml --check
