name: CD

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Get Release Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Deploy to Heroku
        env:
          HEROKU_APP_NAME: 'reading-todo'
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        if: job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git `git subtree split --prefix client $RELEASE_VERSION`:master --force
