name: CI

on:
  push:
    branches:
      - '**'

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14

      - name: Dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          cd client
          yarn lint
      - name: Tests
        run: |
          cd client
          yarn test --coverage --watchAll false
      - name: Build
        run: |
          cd client
          yarn build
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14

      - name: Dependencies
        run: |
          cd api
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          cd api
          yarn lint
      - name: Tests
        run: |
          cd api
          yarn test --coverage --watchAll false
      - name: Build
        run: |
          cd api
          yarn build
