name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14

      - name: Update npm
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Lint React
        run: |
          cd client
          yarn lint
      - name: Run tests
        run: |
          cd client
          yarn test --coverage --watchAll false
      - name: Build Client
        run: |
          cd client
          yarn build
