name: CI-PR

on: [pull_request]

jobs:
  client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}

      - name: Dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          cd client
          yarn lint
      - name: Tests
        run: |
          cd client
          yarn test --coverage --watchAll false
      - name: Build
        run: |
          cd client
          yarn build
  api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}

      - name: Dependencies
        run: |
          cd api
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          cd api
          yarn lint
      - name: Tests
        run: |
          cd api
          yarn test --coverage --watchAll false
      - name: Build
        run: |
          cd api
          yarn build
