name: Client-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build Client
        run: |
          cd client
          npm run test
          npm build
