name: Client-CI

on: [push]

push:
  paths:
    - client/*

jobs:
  build:
    runs-on: ubuntu-latest, macos-latest

    steps:
      - uses: actions/checkout@master
      - name: Build Client
        run: |
          cd client
          npm run test
          npm build
