name: Client-CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}

      - name: Update npm
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Lint React
        run: |
          cd client
          yarn lint
      - name: Run tests
        run: |
          cd client
          yarn test --coverage --watchAll false
      - name: Build Client
        run: |
          cd client
          yarn build
