name: Client

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@main

      - name: Set Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}

      - name: Update npm
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Lint React
        run: |
          cd client
          yarn lint
      - name: Run tests
        run: |
          cd client
          yarn test --coverage --watchAll false
      - name: Build Client
        run: |
          cd client
          yarn build
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: 'reading-todo'
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: git subtree push --prefix client https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git main --force
